### ISSUE TITLE
Request: Acceso a las reservas

### ISSUE THREAD

**Issue by JSnow11** [gii-is-psg2/PSG2-2021-G4-41#113]
## description
Me gustaría que hubiera una forma más directa de poder reservar una habitación para mi mascota.

## to-do
- [x] define the most direct way to book a room
- [x] implement the feature

## accept
- [x] the owners can book a room for their pets easier
