### ISSUE TITLE
T-3.2.b: Booking validation

### ISSUE THREAD

**Issue by JSnow11** [gii-is-psg2/PSG2-2021-G4-41#36]
## description
Implement a validation on the booking creation of your pet hotel functionality that ensures that there are not concurrent bookings in the hotel for the same pet.

## to-do
- [x] chose the validation methodology (exception, custom ...)
- [x] implement the validation

## accept
- [x] add a booking for a period of time
- [x] add a booking that overlaps that period
- [x] some error is displayed 
- [x] ensure there are not concurrent bookings in the hotel for the same pet

**Comment by miggavmar** [comment]
Al no tener conocimientos de DP me resulta complicado hacer esta tarea. No encuentro información en la asignatura ni apoyo en internet para realizarla, asique solicito ayuda de como hacerla. Gracias de antemano
