### ISSUE TITLE
T-3.2.c: Adoptions functionality

### ISSUE THREAD

**Issue by JSnow11** [gii-is-psg2/PSG2-2021-G4-41#37]
## description
Create an Adoptions functionality. As a client, we can create an **adoption request** when we are not able to take care of our pet. Other owners could **list the pets available for adoption** and **apply** (**adoption applications** will have a **description** of how the applicant will take care of the pet). If the original owner **approves** the application, the pet will be **transferred to the applicant** and he/she will be the **new owner** of the pet.

## to-do
- [x] request entity (valid)
- [x] application entity (valid)
- [x] adoptions request repo
- [x] adoptions application repo
- [x] adoptions common service
- [x] adoptions common controller
- [x] views
   - [x] list of requests and request form
   - [x] apply form
   - [x] list of applications to the request with confirm button

## accept

- [ ] any client can make a adoption request
- [ ] the list of adoption requests is public
- [ ] other clients can apply for the adoption
- [ ] the owner can approve any of the applications
- [ ] once an application is approved the pet is transferred to the new owner
